language: php

php:
  - 7.3

before_install:
  - touch database/database.sqlite
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --no-suggest
  - travis_retry npm install

script:
  - npm run production
  - vendor/bin/phpunit
  - vendor/bin/phpcs
