language: php

php:
  - 7.4snapshot

before_install:
  - touch database/database.sqlite
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --no-suggest
  - travis_retry npm install

script:
  - npm run production
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/phpcs

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache
