name: build

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache NPM
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: dependencies-node-${{ hashFiles('package-lock.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest --no-ansi --no-progress

      - name: Install NPM dependencies
        run: npm install --no-audit --no-optional

      - name: Compile assets
        run: npm run build

      - name: Create database
        run: touch database/database.sqlite

      - name: Execute tests
        run: |
          vendor/bin/pint --test -v
          vendor/bin/phpunit --do-not-cache-result

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
